open! Import

(** [infer_exp exp] returns the constraint generated by [exists 'a. [| exp : 'a |]]. *)
val infer_exp : Ast.expression -> Constraint.t Or_error.t

(** [infer_str str] returns the constraint generated by [[| str |]] *)
val infer_str : Ast.structure -> Constraint.t Or_error.t
